#!/usr/bin/env python3
"""Build the offline context rejection gate from the generated deck and jieba."""

from __future__ import annotations

import json
import argparse
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DECK_PATH = ROOT / "deck-data.js"
JIEBA_PATH = ROOT / "sources" / "jieba_dict.txt"
APPROVED_PATH = ROOT / "scripts" / "fixtures" / "context-quality-approved.json"
OUTPUT_PATH = ROOT / "data" / "context-quality.js"


def load_cards() -> list[dict]:
    source = DECK_PATH.read_text(encoding="utf-8")
    marker = "const SEED = "
    start = source.find(marker)
    end = source.find(";\n", start)
    if start < 0 or end < 0:
        raise RuntimeError("SEED not found in deck-data.js")
    return json.loads(source[start + len(marker) : end])


def load_jieba() -> dict[str, tuple[int, frozenset[str]]]:
    frequencies: dict[str, int] = {}
    tags: dict[str, set[str]] = {}
    for line in JIEBA_PATH.read_text(encoding="utf-8").splitlines():
        parts = line.rsplit(" ", 2)
        if len(parts) != 3 or not parts[1].isdigit():
            continue
        word, frequency, tag = parts
        frequencies[word] = max(frequencies.get(word, 0), int(frequency))
        tags.setdefault(word, set()).add(tag)
    return {word: (frequency, frozenset(tags[word])) for word, frequency in frequencies.items()}


def load_approved_words() -> frozenset[str]:
    payload = json.loads(APPROVED_PATH.read_text(encoding="utf-8"))
    if payload.get("schemaVersion") != 1 or not isinstance(payload.get("approvedWords"), dict):
        raise RuntimeError("invalid context-quality-approved.json")
    return frozenset(str(word) for word in payload["approvedWords"])


def rejection_reason(
    card: dict,
    jieba: dict[str, tuple[int, frozenset[str]]],
    approved_words: frozenset[str] = frozenset(),
) -> str:
    target = str(card.get("target", ""))
    word = str(card.get("ans", ""))
    frequency, tags = jieba.get(word, (0, frozenset()))
    if word == target + "字":
        return "placeholder"
    if word in approved_words or "i" in tags:
        return ""
    proper_noun_tags = {"nr", "nrt", "nrfg", "ns", "nt"}
    if tags and tags <= proper_noun_tags and frequency <= 300 and len(word) <= 3:
        return "low_frequency_proper_noun"
    if len(word) >= 4 and frequency <= 300:
        return "low_frequency_long_context"
    return ""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    options = parser.parse_args()
    cards = load_cards()
    jieba = load_jieba()
    approved_words = load_approved_words()
    rejected = {
        card["target"]: reason
        for card in cards
        if (reason := rejection_reason(card, jieba, approved_words))
    }
    counts = Counter(rejected.values())
    summary = {
        "schemaVersion": 1,
        "deckCards": len(cards),
        "rejectedCards": len(rejected),
        "acceptedCards": len(cards) - len(rejected),
        "reasons": dict(sorted(counts.items())),
        "rules": {
            "properNounAllowedTags": ["nr", "nrfg", "nrt", "ns", "nt"],
            "properNounMaximumFrequencyInclusive": 300,
            "properNounMaximumCharacters": 3,
            "longContextMinimumCharacters": 4,
            "longContextMaximumFrequencyInclusive": 300,
            "idiomTagExempted": True,
            "reviewedSafeWords": len(approved_words),
        },
    }
    payload = (
        "// Generated by scripts/build_context_quality.py; do not edit by hand.\n"
        f"const CONTEXT_REJECTED = Object.freeze({json.dumps(rejected, ensure_ascii=False, separators=(',', ':'))});\n"
        f"const CONTEXT_QUALITY_SUMMARY = Object.freeze({json.dumps(summary, ensure_ascii=False, separators=(',', ':'))});\n"
    )
    if options.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != payload:
            raise SystemExit("data/context-quality.js is stale; rebuild it")
    else:
        OUTPUT_PATH.write_text(payload, encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
